import Header from '@/shared/compontents/Header'
import './globals.scss'
import './globals.css'
import Footer from '@/shared/compontents/Footer'
import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Home page',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body>
				<div className='wrapper container'>
					<Header />
					<main className='main'>{children}</main>
					<Footer />
				</div>
			</body>
		</html>
	)
}
