import React from 'react'

import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Pages page',
	description: 'Generated by create next app',
}

const Pages = () => {
	return <p>Pages page</p>
}

export default Pages
