import React from 'react'

import type { Metadata } from 'next'
import UsersList from '@/shared/compontents/PostsList'
import SearchUser from '@/shared/compontents/SearchUser'

export const metadata: Metadata = {
	title: 'Pages page',
	description: 'Generated by create next app',
}

const Pages = () => {
	return (
		<>
			<SearchUser />
			<UsersList />
		</>
	)
}

export default Pages
