import { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
	title: 'Our-Offer',
	description: 'Generated by create next app',
}

const OurOffer = () => {
	return <p>Our Offer</p>
}

export default OurOffer
