import React from 'react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Shop page',
	description: 'Generated by create next app',
}

const Shop = () => {
	return <p>Shop</p>
}

export default Shop
