import React from 'react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Pricing page',
	description: 'Generated by create next app',
}

const Pricing = () => {
	return <p>Pricing page</p>
}

export default Pricing
